# Generated by Django 3.0.1 on 2020-01-02 01:18

import apps.article.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='標籤名稱')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='標題')),
                ('content', models.TextField(blank=True, verbose_name='內文')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='發佈時間')),
                ('changed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改時間')),
                ('category', models.CharField(choices=[('NEWS', '新聞'), ('EVENT', '活動'), ('UPDATE', '更新'), ('SCI', '科普文章'), ('TECH', '技術專欄'), ('PUB', '出版品資料'), ('POS', 'TaiBIF發表文章/海報'), ('STATIC', '靜態頁面')], default='NEWS', max_length=50, verbose_name='分類')),
                ('is_pinned', models.CharField(choices=[('N', '否'), ('Y', '是')], default='N', max_length=2, verbose_name='置頂')),
                ('cover', models.ImageField(blank=True, upload_to=apps.article.models.article_cover_path)),
                ('cover_license_text', models.CharField(blank=True, max_length=100, verbose_name='授權文字')),
                ('memo', models.CharField(blank=True, max_length=128, verbose_name='備註(不會顯示)')),
                ('memo_text', models.TextField(blank=True, verbose_name='備註(多字)')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='article.Tag', verbose_name='標籤')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-created'],
            },
        ),
    ]
