version: '3.7'

services:
  web:
    build: .
    container_name: taibif-web-dev-container
    image: taibif-web-dev-image
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - .:/taibif-code
      - ../taibif-volumes/bucket:/taibif-volumes/bucket
      - ../taibif-volumes/media:/taibif-volumes/media
    command: "./scripts/wait-for-it.sh db:5432 -t 5 -- ./scripts/docker-web-dev-entry.sh"
    #command: "./scripts/wait-for-it.sh db:5432 -t 5 -- ./scripts/docker-web-entry.sh"
    restart: always
    env_file:
      - .env
  db:
    container_name: taibif-db-container
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=taibif
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../taibif-volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ../taibif-volumes/bucket:/taibif-volumes/bucket
  adminer:
    image: adminer
    restart: always
    links:
      - db:db
    ports:
      - 8080:8080
