# Generated by Django 3.0.1 on 2020-02-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20200211_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(default='', verbose_name='網址'),
        ),
    ]
