# Generated by Django 3.0.1 on 2020-02-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20200213_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(default='', verbose_name='網站'),
        ),
    ]
