# Generated by Django 3.0.1 on 2020-02-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20200213_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cat',
            field=models.CharField(default='', max_length=200, verbose_name='網站類型'),
        ),
    ]
