# Generated by Django 3.0.1 on 2020-02-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20200218_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='網站類型'),
        ),
    ]
