# Generated by Django 3.0.1 on 2020-02-18 03:27

import apps.page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20200218_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.ImageField(blank=True, upload_to=apps.page.models.page_image_path),
        ),
    ]
