# Generated by Django 3.0.1 on 2020-02-18 06:00

import apps.page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20200218_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='網站名稱')),
                ('upload', models.ImageField(blank=True, upload_to=apps.page.models.page_image_path)),
                ('url', models.URLField(default='', verbose_name='網站')),
                ('content', models.CharField(blank=True, default='', max_length=200, verbose_name='內容')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='內容'),
        ),
    ]
