# Generated by Django 3.0.4 on 2020-03-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20200218_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['sort'], 'verbose_name': '資料論文/期刊', 'verbose_name_plural': '資料論文/期刊'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['sort'], 'verbose_name': '相關連結', 'verbose_name_plural': '相關連結'},
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(blank=True, choices=[('web', '網站'), ('data', '資料庫')], default='', max_length=200, verbose_name='網站類型'),
        ),
    ]
