# Generated by Django 3.0.7 on 2020-09-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_auto_20200321_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upload',
            new_name='Upload',
        ),
    ]
