# Generated by Django 4.0 on 2022-07-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_auto_20200928_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='content_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='英文說明'),
        ),
        migrations.AddField(
            model_name='journal',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='網站英文名稱'),
        ),
    ]
