# Generated by Django 4.0 on 2022-07-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_journal_content_en_journal_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='英文說明'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='網站英文名稱'),
        ),
    ]
