# Generated by Django 4.2.7 on 2024-12-18 01:53

import apps.page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_post_content_en_post_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='upload',
            field=models.ImageField(blank=True, upload_to=apps.page.models.upload_image_path),
        ),
    ]
