# Generated by Django 4.2.7 on 2026-03-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_alter_journal_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBubbleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='活動資訊活動資訊活動資訊活動資訊活動資訊活動資訊活動資訊活動資訊', max_length=300, verbose_name='說話魚文案')),
                ('url', models.CharField(blank=True, default='', help_text='可使用站內路徑（如 /zh-hant/open-process）或完整網址', max_length=500, verbose_name='說話魚連結')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '首頁說話魚設定',
                'verbose_name_plural': '首頁說話魚設定',
            },
        ),
    ]
