# Generated by Django 4.2.7 on 2026-03-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_index_bubble_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexbubblesetting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
