# Generated by Django 4.2.7 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0017_alter_indexbubblesetting_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="電子信箱")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="訂閱時間")),
            ],
            options={
                "verbose_name": "電子報訂閱名單",
                "verbose_name_plural": "電子報訂閱名單",
                "ordering": ["-created_at"],
            },
        ),
    ]
