# Generated by Django 3.0.1 on 2020-01-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='stats_extensions',
            new_name='extension_data',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='stats_num_occurrence',
            new_name='num_occurrence',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='stats_num_record',
            new_name='num_record',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='versione',
            new_name='organisation',
        ),
        migrations.AddField(
            model_name='dataset',
            name='version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=10, verbose_name='status'),
        ),
    ]
