# Generated by Django 3.0.1 on 2020-01-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200103_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='gbif_mod_date',
            field=models.DateTimeField(null=True, verbose_name='Modified Date from gbif'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], max_length=10, verbose_name='status'),
        ),
    ]
