# Generated by Django 3.0.1 on 2020-01-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200103_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='mod_date',
            field=models.DateTimeField(null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Publish Date'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], max_length=10, verbose_name='status'),
        ),
    ]
