# Generated by Django 3.0.4 on 2020-03-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_taxon_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='rank',
            field=models.CharField(choices=[('kingdom', '界'), ('phylum', '門'), ('class', '綱'), ('order', '目'), ('family', '科'), ('genus', '屬'), ('species', '種')], max_length=32, verbose_name='rank'),
        ),
    ]
