# Generated by Django 3.0.4 on 2020-03-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20200302_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(verbose_name='Description')),
                ('author', models.CharField(max_length=128, verbose_name='author')),
            ],
        ),
        migrations.AddField(
            model_name='datasetorganization',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='datasetorganization',
            name='name',
            field=models.CharField(max_length=512, verbose_name='name'),
        ),
    ]
