# Generated by Django 3.0.4 on 2020-03-09 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20200309_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetorganization',
            name='country_code',
            field=models.CharField(default='TW', max_length=8, verbose_name='country_code'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='data.DatasetOrganization'),
        ),
    ]
