# Generated by Django 3.0.4 on 2020-03-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_auto_20200309_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='is_accepted_name',
            field=models.BooleanField(default=True, verbose_name='is accepted name'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='verbose',
            field=models.CharField(default='', max_length=1000, verbose_name='verbose'),
        ),
    ]
