# Generated by Django 3.0.4 on 2020-03-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_auto_20200314_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='source_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='name_code'),
        ),
    ]
