# Generated by Django 3.0.1 on 2020-02-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_auto_20200218_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], max_length=10, verbose_name='status'),
        ),
    ]
