# Generated by Django 3.0.4 on 2020-03-18 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20200315_0833'),
        ('data', '0027_auto_20200218_1342'),
    ]

    operations = [
    ]
