# Generated by Django 3.0.4 on 2020-03-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20200318_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('Public', '公開'), ('Private', '非公開')], max_length=10, verbose_name='status'),
        ),
    ]
