# Generated by Django 3.0.4 on 2020-03-22 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20200320_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleData',
            fields=[
                ('taibif_id', models.BigIntegerField(primary_key=True)),
                ('year', models.CharField(max_length=10, null=True)),
                ('month', models.CharField(max_length=10, null=True)),
                ('day', models.CharField(max_length=10, null=True)),
                ('taxon_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_data', to='data.Taxon')),
                ('taxon_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_data', to='data.Taxon')),
                ('taxon_genus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genus_data', to='data.Taxon')),
                ('taxon_kingdom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kingdom_data', to='data.Taxon')),
                ('taxon_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_data', to='data.Taxon')),
                ('taxon_phylum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phylum_data', to='data.Taxon')),
                ('taxon_species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_data', to='data.Taxon')),
            ],
        ),
    ]
