# Generated by Django 3.0.4 on 2020-03-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_simpledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpledata',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='coordinates_latitude_decimal'),
        ),
        migrations.AddField(
            model_name='simpledata',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='coordinates_longitude_decimal'),
        ),
    ]
