# Generated by Django 3.0.4 on 2020-03-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_auto_20200323_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpledata',
            name='day',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='simpledata',
            name='month',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='simpledata',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
