# Generated by Django 3.0.4 on 2020-03-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_auto_20200324_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpledata',
            name='country',
            field=models.CharField(max_length=1000, null=True, verbose_name='country'),
        ),
    ]
