# Generated by Django 3.0.4 on 2020-03-24 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_simpledata_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simpledata',
            old_name='taibif_id',
            new_name='taibif',
        ),
    ]
