# Generated by Django 3.0.4 on 2020-03-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_simpledata_taibif_dataset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpledata',
            name='scientific_name',
            field=models.CharField(max_length=1000, null=True, verbose_name='scientific_name'),
        ),
    ]
