# Generated by Django 3.0.4 on 2020-03-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_simpledata_scientific_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpledata',
            name='vernacular_name',
            field=models.CharField(max_length=1000, null=True, verbose_name='vernacular_name'),
        ),
    ]
