# Generated by Django 3.0.5 on 2020-04-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_auto_20200418_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='admin_memo',
            field=models.TextField(blank=True, null=True, verbose_name='後台管理註記'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='has_publish_problem',
            field=models.BooleanField(default=False, verbose_name='是否有發布問題 (IPT 授權沒填)'),
        ),
    ]
