# Generated by Django 3.0.5 on 2020-05-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_auto_20200423_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='specific_epithet',
            field=models.CharField(max_length=128, null=True, verbose_name='specific epithet'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='admin_memo',
            field=models.TextField(blank=True, help_text='不會在前台出現', null=True, verbose_name='後台管理註記'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='has_publish_problem',
            field=models.BooleanField(default=False, help_text='有可能 IPT 授權沒填?', verbose_name='是否有發布問題 (IPT 裡黃色的區塊)'),
        ),
    ]
