# Generated by Django 3.0.5 on 2020-05-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_auto_20200519_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='kingdom',
            field=models.CharField(default='', max_length=128, verbose_name='kingdom'),
        ),
    ]
