# Generated by Django 3.0.5 on 2020-05-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_taxon_kingdom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='kingdom',
        ),
        migrations.AddField(
            model_name='taxon',
            name='kingdom_id',
            field=models.PositiveIntegerField(default=0, verbose_name='kingdom_id'),
        ),
    ]
