# Generated by Django 3.0.5 on 2020-05-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_auto_20200519_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='kingdom_id',
        ),
        migrations.AddField(
            model_name='taxon',
            name='hierarchy_string',
            field=models.CharField(default='', max_length=512, verbose_name='hierarchy string'),
        ),
    ]
