# Generated by Django 3.0.5 on 2020-05-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_auto_20200519_0444'),
        ('data', '0041_auto_20200522_1157'),
    ]

    operations = [
    ]
