# Generated by Django 3.2.5 on 2021-08-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_auto_20210823_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='taieol_desc',
            field=models.TextField(null=True, verbose_name='taieol_desc'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='taieol_pic',
            field=models.CharField(max_length=1000, null=True, verbose_name='taieol_pic'),
        ),
        migrations.DeleteModel(
            name='SimpleData',
        ),
        migrations.DeleteModel(
            name='RawDataOccurrence',
        ),
    ]
