# Generated by Django 3.2.5 on 2021-09-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_auto_20210910_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='classKey',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='familyKey',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='genusKey',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='kingdomKey',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='orderKey',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='phylumKey',
        ),
        migrations.AddField(
            model_name='taxon',
            name='class_id',
            field=models.IntegerField(default=0, null=True, verbose_name='class_id'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='family_id',
            field=models.IntegerField(default=0, null=True, verbose_name='family_id'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='genus_id',
            field=models.IntegerField(default=0, null=True, verbose_name='genus_id'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='kingdom_id',
            field=models.IntegerField(default=0, null=True, verbose_name='kingdom_id'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='order_id',
            field=models.IntegerField(default=0, null=True, verbose_name='order_id'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='phylum_id',
            field=models.IntegerField(default=0, null=True, verbose_name='phylum_id'),
        ),
    ]
