# Generated by Django 3.2.5 on 2021-09-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_alter_dataset_dwc_core_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='name_zh',
            field=models.CharField(max_length=2000, null=True, verbose_name='name_zh'),
        ),
    ]
