# Generated by Django 3.2.5 on 2021-09-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0064_alter_datasetorganization_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetorganization',
            name='administrative_contact',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='administrative_contact'),
        ),
        migrations.AlterField(
            model_name='datasetorganization',
            name='country_or_area',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='country_or_area'),
        ),
        migrations.AlterField(
            model_name='datasetorganization',
            name='endorsed_by',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='endorsed_by'),
        ),
        migrations.AlterField(
            model_name='datasetorganization',
            name='installations',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='installations'),
        ),
        migrations.AlterField(
            model_name='datasetorganization',
            name='technical_contact',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='technical_contact'),
        ),
    ]
