# Generated by Django 3.2.7 on 2021-11-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0068_alter_dataset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='pre_count',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pre_released',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pub_count',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pub_released',
            field=models.DateTimeField(null=True),
        ),
    ]
