# Generated by Django 3.2.7 on 2022-01-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0069_auto_20211108_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='taibifcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('name_c', models.CharField(blank=True, max_length=128, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
