# Generated by Django 3.2.7 on 2022-01-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0070_taibifcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taibifcode',
            old_name='code_id',
            new_name='objid',
        ),
    ]
