# Generated by Django 4.0 on 2022-11-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0081_alter_dataset_is_most_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetorganization',
            name='organization_gbif_uuid',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='organization_gbif_uuid'),
        ),
    ]
