# Generated by Django 4.0 on 2022-12-26 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0082_datasetorganization_organization_gbif_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon_Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_code', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('folder', models.TextField(blank=True, null=True)),
                ('image_name', models.TextField(blank=True, null=True)),
                ('chinese_name', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('photographer', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('taxon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='pic', to='data.taxon')),
            ],
        ),
    ]
