# Generated by Django 4.0 on 2022-12-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0084_taxon_picture_class_id_taxon_picture_family_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon_picture',
            name='license',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon_picture',
            name='taieol_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
