# Generated by Django 4.0 on 2023-01-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0085_taxon_picture_license_taxon_picture_taieol_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='backbone',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='backbone'),
        ),
    ]
