# Generated by Django 4.0 on 2023-04-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0087_taxon_taicol_name_id_taxon_taicol_taxon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='class_taxon_id',
            field=models.CharField(max_length=128, null=True, verbose_name='class_taxon_id'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='family_taxon_id',
            field=models.CharField(max_length=128, null=True, verbose_name='family_taxon_id'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='formatted_name',
            field=models.CharField(max_length=256, null=True, verbose_name='formatted_name'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='genus_taxon_id',
            field=models.CharField(max_length=128, null=True, verbose_name='genus_taxon_id'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='kingdom_taxon_id',
            field=models.CharField(max_length=128, null=True, verbose_name='kingdom_taxon_id'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='name_author',
            field=models.CharField(max_length=256, null=True, verbose_name='name_author'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='order_taxon_id',
            field=models.CharField(max_length=128, null=True, verbose_name='order_taxon_id'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='phylum_taxon_id',
            field=models.CharField(max_length=128, null=True, verbose_name='phylum_taxon_id'),
        ),
    ]
