# Generated by Django 4.0 on 2023-04-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0089_taxon_parent_taxon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='path',
            field=models.TextField(null=True, verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='rank',
            field=models.CharField(choices=[('kingdom', '界'), ('phylum', '門'), ('class', '綱'), ('order', '目'), ('family', '科'), ('genus', '屬'), ('Aberration', 'Aberration'), ('Class', 'Class'), ('Family', 'Family'), ('Form', 'Form'), ('Genus', 'Genus'), ('Hybrid Formula', 'Hybrid Formula'), ('Infraclass', 'Infraclass'), ('Infrakingdom', 'Infrakingdom'), ('Infraorder', 'Infraorder'), ('Infraphylum', 'Infraphylum'), ('Kingdom', 'Kingdom'), ('Nothovariety', 'Nothovariety'), ('Order', 'Order'), ('Phylum', 'Phylum'), ('Section', 'Section'), ('Species', 'Species'), ('Subclass', 'Subclass'), ('Subfamily', 'Subfamily'), ('Subgenus', 'Subgenus'), ('Subkingdom', 'Subkingdom'), ('Suborder', 'Suborder'), ('Subphylum', 'Subphylum'), ('Subsection', 'Subsection'), ('Subspecies', 'Subspecies'), ('Subtribe', 'Subtribe'), ('Subvariety', 'Subvariety'), ('Superclass', 'Superclass'), ('Superfamily', 'Superfamily'), ('Superkingdom', 'Superkingdom'), ('Superorder', 'Superorder'), ('Superphylum', 'Superphylum'), ('Tribe', 'Tribe'), ('Variety', 'Variety'), ('Subfamily', 'Subfamily'), ('Subgenus', 'Subgenus'), ('Subkingdom', 'Subkingdom')], max_length=32, verbose_name='rank'),
        ),
    ]
