# Generated by Django 4.0 on 2023-04-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0090_taxon_path_alter_taxon_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon_picture',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
