# Generated by Django 4.0 on 2023-04-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0091_taxon_picture_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon_picture',
            name='taicol_taxon_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='taicol taxon id'),
        ),
    ]
