# Generated by Django 4.0 on 2023-06-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0095_dataset_taibif_dataset_id_alter_taxon_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='hierarchy_string',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='specific_epithet',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='tree',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='verbose',
        ),
        migrations.AddField(
            model_name='taxon',
            name='alien_type',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='alien_type'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='alternative_name_c',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='alternative_name_c'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='cites',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='cites'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='formatted_misapplied',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='formatted_misapplied'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='formatted_synonyms',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='formatted_synonyms'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='is_brackish',
            field=models.BooleanField(default=False, verbose_name='is_brackish'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='is_endemic',
            field=models.BooleanField(default=False, verbose_name='is_endemic'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='is_fossil',
            field=models.BooleanField(default=False, verbose_name='is_fossil'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='is_freshwater',
            field=models.BooleanField(default=False, verbose_name='is_freshwater'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='is_hybrid',
            field=models.BooleanField(default=False, verbose_name='is_hybrid'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='is_in_taiwan',
            field=models.BooleanField(default=False, verbose_name='is_in_taiwan'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='is_marine',
            field=models.BooleanField(default=False, verbose_name='is_marine'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='is_terrestrial',
            field=models.BooleanField(default=False, verbose_name='is_terrestrial'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='iucn',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='iucn'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='misapplied',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='misapplied'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='new_taxon_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='new_taxon_id'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='protected',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='protected'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='redlist',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='redlist'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='sensitive',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='sensitive'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='formatted_name',
            field=models.CharField(max_length=128, null=True, verbose_name='formatted_name'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='name',
            field=models.CharField(max_length=128, verbose_name='simple_name'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='name_zh',
            field=models.CharField(max_length=256, null=True, verbose_name='common_name_c'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='taicol_taxon_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='taicol taxon id'),
        ),
        migrations.DeleteModel(
            name='TaxonTree',
        ),
    ]
