# Generated by Django 4.0 on 2024-03-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0099_dataset_source_alter_dataset_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='parent_taxon_id_linnaean',
            field=models.CharField(max_length=256, null=True, verbose_name='self'),
        ),
    ]
