# Generated by Django 4.2.7 on 2024-08-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0101_dataset_contact_position_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='rank',
            field=models.CharField(choices=[('Domain', '域'), ('Superkingdom', '總界'), ('kingdom', '界'), ('Subkingdom', '亞界'), ('Infrakingdom', '下界'), ('Superdivision', '超部|總部'), ('Division', '部|類'), ('Subdivision', '亞部|亞類'), ('Infradivision', '下部|下類'), ('Parvdivision', '小部|小類'), ('Superphylum', '超門|總門'), ('phylum', '門'), ('Subphylum', '亞門'), ('Infraphylum', '下門'), ('Microphylum', '小門'), ('Parvphylum', '小門'), ('Superclass', '超綱|總綱'), ('class', '綱'), ('Subclass', '亞綱'), ('Infraclass', '下綱'), ('Superorder', '超目|總目'), ('order', '目'), ('Suborder', '亞目'), ('Infraorder', '下目'), ('Superfamily', '超科|總科'), ('family', '科'), ('Subfamily', '亞科'), ('Tribe', '族'), ('Subtribe', '亞族'), ('genus', '屬'), ('Subgenus', '亞屬'), ('Seection', '亞組|亞節'), ('species', '種'), ('subspecies', '亞種'), ('Nothosubspecies', '雜交亞種'), ('variety', '變種'), ('subvariety', '亞變種'), ('nothovariety', '雜交變種'), ('form', '型'), ('subform', '亞型'), ('special form', '特別品型'), ('Race', '種族'), ('Stirp', '種族'), ('Morph', '形態型'), ('Aberration', '異常個體'), ('hybrid formula', '雜交組合')], max_length=32, verbose_name='rank'),
        ),
    ]
