# Generated by Django 4.2.7 on 2024-08-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0102_alter_taxon_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopValidationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='通過年份')),
                ('level', models.CharField(choices=[('basic', '初階'), ('advanced', '進階')], verbose_name='認證等級')),
                ('name', models.CharField(help_text='（需要手動彌封）', verbose_name='姓名')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='最後修改日期')),
            ],
        ),
    ]
