# Generated by Django 4.2.7 on 2024-08-12 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0103_workshopvalidationlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkshopValidationList',
            new_name='WorkshopCertificationList',
        ),
        migrations.AlterModelOptions(
            name='workshopcertificationlist',
            options={'verbose_name': '歷年工作坊通過認證名單', 'verbose_name_plural': '歷年工作坊通過認證名單'},
        ),
    ]
