# Generated by Django 4.2.7 on 2024-08-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0105_taibifparticipants'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaibiferList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='姓名')),
                ('role', models.TextField(help_text='（若有一個以上的項目，請用全形頓號分隔）', verbose_name='角色類型')),
                ('missions', models.TextField(help_text='（若有一個以上的項目，請用全形頓號分隔）', verbose_name='參與任務')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='最後修改日期')),
            ],
            options={
                'verbose_name': 'TaiBIF 專業人員/志工名單',
                'verbose_name_plural': 'TaiBIF 專業人員/志工名單',
            },
        ),
    ]
