# Generated by Django 4.2.7 on 2024-08-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0106_taibiferlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPaperList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='文章標題')),
                ('journal', models.CharField(verbose_name='發表期刊')),
                ('article_doi', models.CharField(help_text='（請填入 doi 即可，例：10.3897/BDJ.10.e90196。前端會自動轉換成連結）', verbose_name='文章 doi')),
                ('dataset_doi', models.CharField(help_text='（請填入 doi 即可，例：10.15468/43z4mj。前端會自動轉換成連結）', verbose_name='資料集 doi')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='最後修改日期')),
            ],
            options={
                'verbose_name': 'TaiBIF 歷年合作資料論文',
                'verbose_name_plural': 'TaiBIF 歷年合作資料論文',
            },
        ),
    ]
