# Generated by Django 4.2.7 on 2024-08-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0107_datapaperlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapaperlist',
            name='title',
            field=models.TextField(verbose_name='文章標題'),
        ),
    ]
