# Generated by Django 4.2.7 on 2024-08-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0111_alter_datasetorganization_administrative_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetorganization',
            name='administrative_contact',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='行政聯絡人'),
        ),
        migrations.AlterField(
            model_name='datasetorganization',
            name='country_code',
            field=models.CharField(blank=True, default='TW', max_length=8, null=True, verbose_name='國家代碼'),
        ),
        migrations.AlterField(
            model_name='datasetorganization',
            name='country_or_area',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='國家或區域'),
        ),
        migrations.AlterField(
            model_name='datasetorganization',
            name='dataset_num',
            field=models.IntegerField(blank=True, default=0, help_text='(目前已不維護)', null=True, verbose_name='資料集數量'),
        ),
        migrations.AlterField(
            model_name='datasetorganization',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='單位描述'),
        ),
        migrations.AlterField(
            model_name='datasetorganization',
            name='endorsed_by',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='發布單位認證節點'),
        ),
        migrations.AlterField(
            model_name='datasetorganization',
            name='installations',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='發布節點'),
        ),
        migrations.AlterField(
            model_name='datasetorganization',
            name='occurences_num',
            field=models.IntegerField(blank=True, default=0, help_text='(目前已不維護)', null=True, verbose_name='出現紀錄筆數'),
        ),
        migrations.AlterField(
            model_name='datasetorganization',
            name='technical_contact',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='技術連絡人'),
        ),
    ]
