# Generated by Django 4.2.7 on 2024-08-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0112_alter_datasetorganization_administrative_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapaperlist',
            name='year',
            field=models.IntegerField(default=2024, help_text='（會依照發布年份顯示在前台，由新至舊排序）', verbose_name='發布年份'),
            preserve_default=False,
        ),
    ]
