# Generated by Django 4.2.7 on 2024-08-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0113_datapaperlist_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapaperlist',
            name='year',
            field=models.IntegerField(help_text='（會依照發布年份顯示在前端，由新至舊排序）', verbose_name='發布年份'),
        ),
    ]
