# Generated by Django 4.2.7 on 2024-11-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0114_alter_datapaperlist_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiBIFerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='角色名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='角色描述')),
            ],
            options={
                'verbose_name': 'TaiBIFer 角色',
                'verbose_name_plural': 'TaiBIFer 角色',
            },
        ),
        migrations.CreateModel(
            name='Taibifer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='姓名')),
                ('year', models.IntegerField(help_text='（會依照發布年份顯示在前端，由新至舊排序）', verbose_name='認證年份')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='最後修改日期')),
                ('roles', models.ManyToManyField(to='data.taibiferrole', verbose_name='TaiBIFer 類型')),
            ],
            options={
                'verbose_name': 'TaiBIFer 志工名單',
                'verbose_name_plural': 'TaiBIFer 志工名單',
            },
        ),
    ]
