# Generated by Django 4.2.7 on 2024-11-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0115_taibiferrole_taibifer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taibifer',
            name='roles',
            field=models.ManyToManyField(to='data.taibiferrole', verbose_name='TaiBIFer 角色'),
        ),
    ]
