# Generated by Django 4.2.7 on 2024-12-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0116_alter_taibifer_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopcertificationlist',
            name='level',
            field=models.CharField(choices=[('basic', '核心'), ('advanced', '增能')], verbose_name='認證等級'),
        ),
    ]
