# Generated by Django 4.2.7 on 2026-03-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0118_datasetupdateevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetupdateevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
