# Generated by Django 3.0.1 on 2020-01-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_homepage',
            field=models.BooleanField(null=True, verbose_name='首頁專題文章'),
        ),
    ]
