# Generated by Django 3.0.4 on 2020-03-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200318_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_content_markdown',
            field=models.BooleanField(blank=True, help_text='舊文章要特別勾, 才會有 markdown 顯示', null=True, verbose_name='內文是否 markdown'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='新文章預設都是 markdown 顯示', verbose_name='內文'),
        ),
    ]
