# Generated by Django 3.0.7 on 2020-09-28 05:53

import apps.article.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200320_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, upload_to=apps.article.models.article_cover_path)),
                ('cover_license_text', models.CharField(blank=True, max_length=100, verbose_name='授權文字')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
        ),
    ]
