# Generated by Django 3.2.5 on 2021-08-23 06:52

import apps.article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(blank=True, upload_to=apps.article.models.images_path),
        ),
    ]
