# Generated by Django 4.0 on 2022-07-15 07:48

import apps.article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_postimage_image_uuid_alter_postimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, help_text='注：圖片尺寸誤過長', upload_to=apps.article.models.article_cover_path),
        ),
    ]
