# Generated by Django 4.2.7 on 2024-05-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('NEWS', '新聞'), ('EVENT', '活動'), ('UPDATE', '更新'), ('SCI', '科普文章'), ('TECH', '技術專欄'), ('PUB', '出版品資料'), ('POS', 'TaiBIF發表文章/海報'), ('STATIC', '靜態頁面'), ('STORY', '資料故事')], default='NEWS', max_length=50, verbose_name='分類'),
        ),
    ]
