# Generated by Django 4.2.7 on 2024-08-05 02:15

import apps.article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_data_case',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否為應用案例'),
        ),
        migrations.AddField(
            model_name='article',
            name='media_url',
            field=models.TextField(blank=True, null=True, verbose_name='多媒體檔案連結'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, help_text='注：圖片尺寸勿過長', upload_to=apps.article.models.article_cover_path),
        ),
    ]
