# Generated by Django 4.2.7 on 2024-08-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_article_is_data_case_article_media_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('NEWS', '新聞'), ('EVENT', '活動'), ('UPDATE', '更新'), ('SCI', '科普'), ('TECH', '技術專欄'), ('PUB', '出版品資料'), ('POS', 'TaiBIF發表文章/海報'), ('STATIC', '靜態頁面'), ('STORY', '資料故事'), ('HACKSON', '數據松')], default='NEWS', max_length=50, verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_data_case',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否為應用案例'),
        ),
        migrations.AlterField(
            model_name='article',
            name='media_url',
            field=models.TextField(blank=True, default='', verbose_name='多媒體檔案連結'),
            preserve_default=False,
        ),
    ]
