# Generated by Django 4.2.7 on 2024-08-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_alter_article_category_alter_article_is_data_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_data_case',
            field=models.BooleanField(blank=True, choices=[('N', '否'), ('Y', '是')], default=False, verbose_name='是否為應用案例'),
        ),
    ]
