# Generated by Django 4.2.7 on 2024-08-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_alter_article_is_data_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_data_case',
            field=models.BooleanField(default=False, verbose_name='是否為應用案例'),
        ),
    ]
