# Generated by Django 4.2.7 on 2024-08-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_alter_article_is_data_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_data_case',
            field=models.BooleanField(default=False, help_text='（勾選後才會呈現在 資料應用案例 頁面上）', verbose_name='是否為應用案例'),
        ),
    ]
