# Generated by Django 4.2.7 on 2024-08-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_alter_article_is_data_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='case_type',
            field=models.CharField(choices=[('HACKSON', '數據松')], default='HACKSON', max_length=50, verbose_name='案例類型'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('NEWS', '新聞'), ('EVENT', '活動'), ('UPDATE', '更新'), ('SCI', '科普'), ('TECH', '技術專欄'), ('PUB', '出版品資料'), ('POS', 'TaiBIF發表文章/海報'), ('STATIC', '靜態頁面'), ('STORY', '資料故事')], default='NEWS', max_length=50, verbose_name='分類'),
        ),
    ]
