# Generated by Django 4.2.7 on 2024-08-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_article_case_type_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='case_type',
            field=models.CharField(blank=True, choices=[('HACKSON', '數據松')], max_length=50, verbose_name='案例類型'),
        ),
    ]
