# Generated by Django 4.2.7 on 2024-08-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_alter_article_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='media_url',
            field=models.TextField(blank=True, help_text='（若為以上應用案例打勾，請選擇案例類型）', verbose_name='多媒體檔案連結'),
        ),
    ]
