# Generated by Django 4.2.7 on 2024-08-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_alter_article_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='case_type',
            field=models.CharField(blank=True, choices=[('HACKSON', '數據松')], help_text='（若為以上應用案例打勾，請選擇案例類型）', max_length=50, verbose_name='案例類型'),
        ),
        migrations.AlterField(
            model_name='article',
            name='media_url',
            field=models.TextField(blank=True, verbose_name='多媒體檔案連結'),
        ),
    ]
