# Generated by Django 4.2.7 on 2024-08-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_alter_article_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('NEWS', '新聞'), ('EVENT', '活動'), ('SCI', '科普'), ('PUB', '出版品'), ('POS', 'TaiBIF 成果'), ('STORY', '資料故事')], default='NEWS', max_length=50, verbose_name='分類'),
        ),
    ]
