# Generated by Django 4.2.7 on 2024-11-29 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_alter_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='案例類型名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '應用案例類型',
                'verbose_name_plural': '應用案例類型',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='new_case_type',
            field=models.ForeignKey(blank=True, help_text='（若為以上應用案例打勾，請選擇案例類型）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.casetype'),
        ),
    ]
