# Generated by Django 4.2.7 on 2024-11-29 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_casetype_article_new_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='new_case_type',
            field=models.ForeignKey(blank=True, help_text='（若為以上應用案例打勾，請選擇案例類型）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.casetype', verbose_name='應用案例類型'),
        ),
    ]
