# Generated by Django 4.2.7 on 2024-11-29 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_alter_article_new_case_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.TextField(blank=True, verbose_name='多媒體檔案連結')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
        ),
    ]
