# Generated by Django 4.2.7 on 2024-11-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0026_casemedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casemedia',
            options={'verbose_name': '案例多媒體', 'verbose_name_plural': '案例多媒體'},
        ),
    ]
