# Generated by Django 4.2.7 on 2024-11-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0027_alter_casemedia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemedia',
            name='media_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='多媒體名稱'),
        ),
        migrations.AlterField(
            model_name='casemedia',
            name='media_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='多媒體檔案連結'),
        ),
    ]
