# Generated by Django 4.2.7 on 2024-11-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0028_casemedia_media_name_alter_casemedia_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemedia',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='case_media', to='article.article'),
        ),
    ]
