# Generated by Django 3.0.1 on 2020-02-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
