# Generated by Django 3.0.1 on 2020-02-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200211_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='網站名稱'),
        ),
    ]
