name: GitHub Actions Demo
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: deploy over ssh
        run: "ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST}} ls -al"
