name: Deploy Staging

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: Deploy
      - run: whoami
